# Generated by Django 5.2.4 on 2025-09-17 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=255)),
                ('repo_link', models.URLField(max_length=2000)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('fastapi_response', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
