# Generated by Django 5.2.4 on 2025-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentDeployer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
